### ISSUE TITLE
Cannot download loopback-connector-crate

### ISSUE THREAD

**Issue by vietanh85** [schwendinger/node-loopback-crate-example#1]
Hi Schwendinger,

I would like to try the loopback-connector-crate, but it has been removed by Lovely Systems. Is there anyway to get it?

Thank you so much,
Anh.

**Comment by agungf** [comment]
Hi Schwendinger,

can you include the loopback-connector-crate to this repo? 

Thank you in advance,
AF

**Comment by jukart** [comment]
Hello.
Sorry that the loopback connector is not released yet but it is now on the way.
We will open the repository within the next 2 weeks hopefully earlier.

Jürgen

**Comment by agungf** [comment]
Hi Jürgen,

Thankyou for the effort, btw can you simply share the initial code so we can contribute?

AF

**Comment by agungf** [comment]
Hi All,

Have just push initial commit to https://github.com/jagad/loopback-connector-crate
welcome for everyone to contribute

best regards,
AF

**Comment by vietanh85** [comment]
Hi Jürgen Kartnaller,
Do you have any update on this?

Thank you,
Anh.

**Comment by jukart** [comment]
I just opened the repository https://github.com/lovelysystems/loopback-connector-crateio

I also published the first version as an npm package. It can not be used because there is a packaging problem wich I just try to resolve now.

Compared to the connector from agungf at https://github.com/jagad/loopback-connector-crate it contains some more features.

@agungf maybe we can merge functionality between our repositories

The tests will reflect which functionality is implemented.

**Comment by jukart** [comment]
Btw. I'm also updating the demo to use the new npm package.

**Comment by jukart** [comment]
loopback-connector-crateio is now deployed and can be installed using npm.

see: https://www.npmjs.com/package/loopback-connector-crateio

**Comment by vietanh85** [comment]
Great, Thank you so much for your effort.

Anh.
